apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: mysql
---  
kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend
  namespace: expense
  # these labels are deployment related labels
  labels:
    component: backend
    project: expense
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      component: backend
      project: expense
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        component: backend
        project: expense
        tier: backend
        environment: dev
    spec:
      containers:
      - name: backend
        image: mallurumamatha/backend:v1.0 ### give the image which you build from docker
        envFrom:
        - configMapRef:
            name: backend

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    component: backend
    project: expense
    tier: backend
    environment: dev
  ports:
  - protocol: TCP
    port: 8080 #service-port
    targetPort: 8080 #target-port