### Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense  # "Namespace" should be "namespace" (lowercase)
spec:
  clusterIP: None  # "clusterIp" should be "clusterIP" (case-sensitive)
  selector:  # Corrected key (singular, not plural)
    app: mysql 
    project: expense
    tier: db
  ports:
  - protocol: TCP  # "tcp" should be uppercase "TCP"
    port: 3306
    targetPort: 3306  # "targetPort" needs to be in camel case

---
### Standard Service to access the pods from outside of the cluster
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql 
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306  # service-port
    targetPort: 3306  # target-port

---
## StatefulSet 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql 
      project: expense
      tier: db 
  serviceName: "mysql-headless"  # Headless service name required for StatefulSet
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql 
        project: expense
        tier: db  
    spec:
      containers:
      - name: mysql
        image: mallurumamatha/mysql:v1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:  # Proper indentation here (aligned with spec)
  - metadata:
      name: mysql
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "expense-sc"
      resources:
        requests:
          storage: 1Gi
