### Headless Service
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: expense  
spec:
  clusterIP: None  
  selector:  
    project: expense
    tier: db
  ports:
  - protocol: TCP  
    port: 3306
    targetPort: 3306  

---
### Standard Service to access the pods from outside of the cluster
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql 
    project: expense
    tier: db
  ports:
  - protocol: TCP
    port: 3306  
    targetPort: 3306  

---
## StatefulSet 
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      app: mysql 
      project: expense
      tier: db 
  serviceName: "mysql-headless"  
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql 
        project: expense
        tier: db  
    spec:
      containers:
      - name: mysql
        image: mallurumamatha/mysql:v1.0
        imagePullPolicy: Always
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates: 
  - metadata:
      name: mysql
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "expense-sc"
      resources:
        requests:
          storage: 1Gi
